### ISSUE TITLE
mvtboost: new gbm release pending

### ISSUE THREAD

**Issue by pdmetcalfe** [patr1ckm/mvtboost#1]
We're coming up to a new release of gbm which considerably tidies the code and introduces a much stricter NAMESPACE. As part of this we have unfortunately had to change the API, and it looks like it's going to break your package.

The new gbm is at

https://github.com/gbm-developers/gbm

Would it be possible for you to take a look?

[00install.out.txt](https://github.com/patr1ckm/mvtboost/files/535642/00install.out.txt)

**Comment by patr1ckm** [comment]
Thanks! I'll take a look and fix it. Excited for the new gbm, looks great.

**Comment by patr1ckm** [comment]
@pdmetcalfe 

On one of my branches, I have a version of my code consistent with gbm 2.2. When do you expect to push it to CRAN?

**Comment by patr1ckm** [comment]
I've made the master branch consistent with gbm 2.2, so I'm closing the issue. Looking forward to release!
