### ISSUE TITLE
Parallelization 

### ISSUE THREAD

**Issue by schelhorn** [patr1ckm/mvtboost#2]
Hello, is parallelization via `parallel` and `mcapply` really enabled? The `mc.cores` argument doesn't seem to work in my setup, and I couldn't find the parallel call in your code. Thanks!

**Comment by patr1ckm** [comment]
Thanks for alerting me to this. I've added parallelization for CV back in via `parallel::mclapply`, as originally documented. You can install the new version from github.

I'm planning a larger release in the next year that will make the parallelization work on Windows as well.
